
[[_Usage]]
= Usage

The following sections describe how you may use this plugin in a project.

== Configuration

You must create a configuration file named `Jcouchdb` that holds the settings for creating instances of `org.jcouchdb.db.Database`.
This file follows the same standard configuration mechanism as the application's `Config` file, which means you can define the
configuration using

 * a properties file
 * a Java file
 * a Groovy script

The following example shows the default settings needed to connect the default database taking into account that each
environment may connect to a different database.

[source,groovy,options="nowrap"]
.src/main/resources/Jcouchdb.groovy
----
include::{path_griffon_jcouchdb_core}/src/test/resources/Jcouchdb.groovy[lines=16..36]
----

You may configure multiple named databases (the default factory is aptly named `default`) as the following snippet
shows

[source,groovy,options="nowrap"]
.src/main/resources/Jcouchdb.groovy
----
include::{path_griffon_jcouchdb_core}/src/test/resources/Jcouchdb.groovy[lines=38..45]
----

The following properties are optional

[cols="4*",options="header"]
|===
| Property           | Type    | Default | Description
| connect_on_startup | boolean | false   | Establishes a connection to the database at the beginning of the `Startup` phase.
|===

The plugin's <<_modules, module>> registers a `{api_database_handler}` helper class that defines the base contract
for accessing a database and issue SQL queries to it. This class has the following methods

[source,java,options="nowrap"]
.griffon.plugins.jcouchdb.DatabaseHandler.java
----
include::{path_griffon_jcouchdb_core}/src/main/java//griffon/plugins/jcouchdb/DatabaseHandler.java[tags=methods,indent=0]
----

These method are aware of multiple databases. If no databaseName is specified when calling them then the default
database will be selected. You can inject an instance of this class anywhere it's needed using `@Inject`. There is one
callback you may use with this method: `{api_database_callback}`.

This callback is defined using a functional interface approach, which means you can apply lambda expressions if running
with JDK8+ or closures if running Groovy.

[source,java,options="nowrap"]
.griffon.plugins.jcouchdb.DatabaseCallback.java
----
include::{path_griffon_jcouchdb_core}/src/main/java/griffon/plugins/jcouchdb/DatabaseCallback.java[lines=26..-1]
----

=== Bootstrap

You may execute arbitrary database calls during connection and disconnection from a `org.jcouchdb.db.Database`. Simply
create a class that implements the `{api_jcouchdb_bootstrap}` interface and register it within a module, for example

[source,java,options="nowrap"]
.src/main/java/com/acme/SampleJcouchdbBootstrap.java
----
package com.acme;

import griffon.plugins.jcouchdb.JcouchdbBootstrap;
import org.jcouchdb.db.Database;

import javax.annotation.Nonnull;
import javax.inject.Named;

@Named("sample")
public class SampleJcouchdbBootstrap implements JcouchdbBootstrap {
    @Override
    public void init(@Nonnull String databaseName, @Nonnull Database database) {
        // operations after first connection to database
    }

    @Override
    public void destroy(@Nonnull String databaseName, @Nonnull Database database) {
        // operations before disconnecting from the database
    }
}
----

[source,java,options="nowrap"]
.src/main/java/com/acme/ApplicationModule.java
----
package com.acme;

import griffon.plugins.jcouchdb.JcouchdbBootstrap;
import griffon.core.injection.Module;
import org.codehaus.griffon.runtime.core.injection.AbstractModule;
import org.kordamp.jipsy.ServiceProviderFor;

@ServiceProviderFor(Module.class)
public class ApplicationModule extends AbstractModule {
    @Override
    protected void doConfigure() {
        bind(JcouchdbBootstrap.class)
            .to(SampleJcouchdbBootstrap.class)
            .asSingleton();
    }
}
----

== Example

The following is a trivial usage of the `{api_database_handler}` inside a Java service

[source,java,options="nowrap"]
.com.acme.SampleService.java
----
package com.acme;

import griffon.core.artifact.GriffonService;
import griffon.metadata.ArtifactProviderFor;
import org.codehaus.griffon.runtime.core.artifact.AbstractGriffonService;

import griffon.plugins.jcouchdb.DatabaseHandler;
import griffon.plugins.jcouchdb.DatabaseCallback;
import org.jcouchdb.db.Database;

import javax.annotation.Nonnull;
import javax.inject.Inject;

@ArtifactProviderFor(GriffonService.class)
public class SampleService extends AbstractGriffonService {
    @Inject
    private DatabaseHandler databaseHandler;

    public String getPersonName(final int id) {
         return databaseHandler.withDatabase(new DatabaseCallback<String>() {
             public String handle(@Nonnull String databaseName, @Nonnull Database database) {
                 ...
         });
    }
}
----

Here's the Groovy version of it

[source,groovy,options="nowrap"]
.com.acme.SampleService.groovy
----
package com.acme

import griffon.core.artifact.GriffonService
import griffon.metadata.ArtifactProviderFor

import griffon.plugins.jcouchdb.DatabaseHandler

import javax.inject.Inject

@ArtifactProviderFor(GriffonService)
class SampleService {
    @Inject
    private DatabaseHandler databaseHandler

    String getPersonName(int id) {
         databaseHandler.withDatabase { String databaseName, Database database ->
             ...
         }
    }
}
----

== Events

The following events will be triggered by `{api_database_handler}`

JcouchdbConnectStart(String databaseName, Map<String, Object> config):: Triggered before connecting to the database.
ConfigureJcouchdbJSONParser(String databaseName, Map<String, Object> config, JSONParser parser):: Triggered when configurating the JSON parser
JcouchdbConnectEnd(String databaseName, Map<String, Object> config, Database database):: Triggered after connecting to the database.
JcouchdbDisconnectStart(String databaseName, Map<String, Object> config, Database database):: Triggered before disconnecting from the database.
JcouchdbDisconnectEnd(String databaseName, Map<String, Object> config):: Triggered after disconnecting from the database.

NOTE: DataSource events may be triggered during connection and disconnection from a `org.jcouchdb.db.Database`.

== AST Transformation

You can apply the `{api_database_aware}` AST transformation on any class. This injects the behavior of `{api_database_handler}`
into said class. The previous Groovy service example can be rewritten as follows

[source,groovy,options="nowrap"]
.com.acme.SampleService.groovy
----
package com.acme

import griffon.core.artifact.GriffonService
import griffon.metadata.ArtifactProviderFor
import griffon.transform.JcouchdbAware

import org.jcouchdb.db.Database

@JcouchdbAware
@ArtifactProviderFor(GriffonService)
class SampleService {
    String getPersonName(int id) {
         withDatabase { String databaseName, Database database ->
             ...
         }
    }
}
----

== DSL Descriptors

This plugin provides DSL descriptors for Intellij IDEA and Eclipse (provided you have the Groovy Eclipse plugin installed).
These descriptors are found inside the `griffon-jcouchdb-groovy-compile-{project-version}.jar`, with locations

 * dsdl/griffon_jcouchdb.dsld
 * gdsl/griffon_jcouchdb.gdsl
